export const GET_RECEIVE_MESSAGE = "GET_RECEIVE_MESSAGE";
export const GET_NEW_CONVERSATION = "GET_NEW_CONVERSATION";
export const GET_ACTIVE_USERS = "GET_ACTIVE_USERS";
export const UPDATE_CONVERSATION_LIST = "UPDATE_CONVERSATION_LIST";
export const GET_NEW_NOTIFICATION = "GET_NEW_NOTIFICATION";
export const CLEAN_SOCKET_STATES = "CLEAN_SOCKET_STATES";
