package com.vivacon.entity.enum_type;

public enum NotificationType {

    REPLY_ON_COMMENT,

    COMMENT_ON_POST,

    AWARE_ON_COMMENT,

    LIKE_ON_POST,

    FOLLOWING_ON_ME,

    POST_REPORT_APPROVING_ACTION_AUTHOR,

    POST_REPORT_APPROVING_DOMAIN_AUTHOR,

    COMMENT_REPORT_APPROVING_ACTION_AUTHOR,

    COMMENT_REPORT_APPROVING_DOMAIN_AUTHOR,

    ACCOUNT_REPORT_APPROVING_ACTION_AUTHOR,

    ACCOUNT_REPORT_APPROVING_DOMAIN_AUTHOR
}
